<?php
defined( 'ABSPATH' ) || exit;

return ['x-generator'=>'aGo Migrator','translation-revision-date'=>'2026-03-17','plural-forms'=>'nplurals=2; plural=n != 1;','project-id-version'=>'aGo Migrator 1.0.0','language'=>'pt-BR','messages'=>[
'aGo Tools'=>'aGo Ferramentas',
'Export full site'=>'Exportar site completo',
'Generates a ZIP file with the complete database, plugins, themes, uploads, users and all configuration.'=>'Gera um arquivo ZIP com o banco de dados completo, plugins, temas, uploads, usuarios e toda a configuracao.',
'Export Backup'=>'Exportar Backup',
'Import backup'=>'Importar backup',
'Drag a ZIP file generated by aGo Migrator or select it manually.'=>'Arraste um arquivo ZIP gerado pelo aGo Migrator ou selecione manualmente.',
'Drag your .zip file here'=>'Arraste seu arquivo .zip aqui',
'or'=>'ou',
'WARNING:'=>'ATENCAO:',
'This will REPLACE the entire current site: database, plugins, themes, media and users. There is no going back.'=>'Isso SUBSTITUIRA todo o site atual: banco de dados, plugins, temas, midia e usuarios. Nao ha como voltar atras.',
'I understand that the entire site will be replaced'=>'Entendo que todo o site sera substituido',
'Confirm & Import'=>'Confirmar e Importar',
'About'=>'Sobre',
'Full-site backup & migration plugin. Export everything, import anywhere. No limits, no subscriptions.'=>'Plugin de backup e migracao completa. Exporte tudo, importe em qualquer lugar. Sem limites, sem assinaturas.',
'Complete database (all tables)'=>'Banco de dados completo (todas as tabelas)',
'Plugins, themes, uploads'=>'Plugins, temas, uploads',
'Users and passwords'=>'Usuarios e senhas',
'Serialization-safe URL replace'=>'Substituicao de URLs segura para dados serializados',
'Standard ZIP format'=>'Formato ZIP padrao',
'WP-CLI support'=>'Suporte WP-CLI',
'Support Open Source'=>'Apoie o Open Source',
'If this plugin saves you time, consider supporting our open-source work.'=>'Se este plugin economiza seu tempo, considere apoiar nosso trabalho open-source.',
'Buy us a coffee'=>'Pague-nos um cafe',
'Voluntary donation. Thank you!'=>'Doacao voluntaria. Obrigado!',
'Developed with %1$s by %2$s'=>'Desenvolvido com %1$s por %2$s',
'Building tools for the web, one plugin at a time.'=>'Construindo ferramentas para a web, um plugin de cada vez.',

'Migrator'=>'Migrator',
'aGo Migrator'=>'aGo Migrator',
]];
