<?php
defined( 'ABSPATH' ) || exit;

return ['x-generator'=>'aGo Migrator','translation-revision-date'=>'2026-03-17','plural-forms'=>'nplurals=2; plural=n != 1;','project-id-version'=>'aGo Migrator 1.0.0','language'=>'es','messages'=>[
'aGo Tools'=>'aGo Herramientas',
'Export full site'=>'Exportar sitio completo',
'Generates a ZIP file with the complete database, plugins, themes, uploads, users and all configuration.'=>'Genera un archivo ZIP con la base de datos completa, plugins, themes, uploads, usuarios y toda la configuracion.',
'Export Backup'=>'Exportar Backup',
'Import backup'=>'Importar backup',
'Drag a ZIP file generated by aGo Migrator or select it manually.'=>'Arrastra un archivo ZIP generado por aGo Migrator o seleccionalo manualmente.',
'Drag your .zip file here'=>'Arrastra tu archivo .zip aqui',
'or'=>'o',
'WARNING:'=>'ATENCION:',
'This will REPLACE the entire current site: database, plugins, themes, media and users. There is no going back.'=>'Esto REEMPLAZARA todo el sitio actual: base de datos, plugins, themes, media y usuarios. No hay vuelta atras.',
'I understand that the entire site will be replaced'=>'Entiendo que se reemplazara todo el sitio',
'Confirm & Import'=>'Confirmar e Importar',
'About'=>'Acerca de',
'Full-site backup & migration plugin. Export everything, import anywhere. No limits, no subscriptions.'=>'Plugin de backup y migracion completa. Exporta todo, importa en cualquier lugar. Sin limites, sin suscripciones.',
'Complete database (all tables)'=>'Base de datos completa (todas las tablas)',
'Plugins, themes, uploads'=>'Plugins, themes, uploads',
'Users and passwords'=>'Usuarios y contraseñas',
'Serialization-safe URL replace'=>'Reemplazo de URLs seguro para datos serializados',
'Standard ZIP format'=>'Formato ZIP estandar',
'WP-CLI support'=>'Soporte WP-CLI',
'Support Open Source'=>'Apoya el Open Source',
'If this plugin saves you time, consider supporting our open-source work.'=>'Si este plugin te ahorra tiempo, considera apoyar nuestro trabajo open-source.',
'Buy us a coffee'=>'Invitanos un cafe',
'Voluntary donation. Thank you!'=>'Donacion voluntaria. Gracias!',
'Developed with %1$s by %2$s'=>'Desarrollado con %1$s por %2$s',
'Building tools for the web, one plugin at a time.'=>'Construyendo herramientas para la web, un plugin a la vez.',

'Migrator'=>'Migrator',
'aGo Migrator'=>'aGo Migrator',
]];
