<?php

namespace AgoLab\Migrator\Admin;

defined( 'ABSPATH' ) || exit;

class Page {

    public static function render(): void {
        ?>
        <div class="wrap">
            <h1>
                <img src="<?php echo esc_url( AGOMIGRATOR_URL . 'assets/img/agolab.webp' ); ?>" alt="aGo Lab" style="height:28px;width:auto;vertical-align:middle;margin-right:8px">
                <?php esc_html_e( 'aGo Migrator', 'ago-migrator' ); ?>
                <span style="font-size:12px;color:#999;margin-left:8px">v<?php echo esc_html( AGOMIGRATOR_VERSION ); ?></span>
            </h1>

            <div class="ago-layout">
                <div class="ago-main">

                    <div class="card ago-card">
                        <h2><?php esc_html_e( 'Export full site', 'ago-migrator' ); ?></h2>
                        <p><?php esc_html_e( 'Generates a ZIP file with the complete database, plugins, themes, uploads, users and all configuration.', 'ago-migrator' ); ?></p>
                        <button id="ago-export-btn" class="button button-primary button-hero">
                            <?php esc_html_e( 'Export Backup', 'ago-migrator' ); ?>
                        </button>

                        <div id="ago-export-progress" class="ago-progress-wrap" style="display:none">
                            <div class="ago-progress-bar" id="ago-export-bar"></div>
                        </div>
                        <p id="ago-export-status" class="ago-status"></p>
                    </div>

                    <div class="card ago-card">
                        <h2><?php esc_html_e( 'Import backup', 'ago-migrator' ); ?></h2>
                        <p><?php esc_html_e( 'Drag a ZIP file generated by aGo Migrator or select it manually.', 'ago-migrator' ); ?></p>

                        <div id="ago-import-dropzone" class="ago-dropzone">
                            <p><?php esc_html_e( 'Drag your .zip file here', 'ago-migrator' ); ?></p>
                            <p><?php esc_html_e( 'or', 'ago-migrator' ); ?></p>
                            <input type="file" id="ago-import-file" accept=".zip" />
                        </div>

                        <div id="ago-import-info" style="display:none">
                            <div class="notice notice-warning inline" style="margin:12px 0">
                                <p><strong><?php esc_html_e( 'WARNING:', 'ago-migrator' ); ?></strong>
                                <?php esc_html_e( 'This will REPLACE the entire current site: database, plugins, themes, media and users. There is no going back.', 'ago-migrator' ); ?></p>
                            </div>
                            <div id="ago-import-manifest" class="ago-manifest"></div>
                            <label style="display:block;margin:12px 0">
                                <input type="checkbox" id="ago-import-confirm-check" />
                                <?php esc_html_e( 'I understand that the entire site will be replaced', 'ago-migrator' ); ?>
                            </label>
                            <button id="ago-import-confirm-btn" class="button button-primary" disabled>
                                <?php esc_html_e( 'Confirm & Import', 'ago-migrator' ); ?>
                            </button>
                        </div>

                        <div id="ago-import-progress" class="ago-progress-wrap" style="display:none">
                            <div class="ago-progress-bar" id="ago-import-bar"></div>
                        </div>
                        <p id="ago-import-status" class="ago-status"></p>
                    </div>

                    <div id="ago-log" class="ago-log" style="display:none"></div>

                </div>

                <div class="ago-sidebar">

                    <div class="card ago-card">
                        <h3><?php esc_html_e( 'Quick links', 'ago-migrator' ); ?></h3>
                        <ul class="ago-features" style="list-style:none;padding:0;margin:0">
                            <li><a href="https://ago.cl/herramientas/wordpress/ago-migrator/docs" target="_blank" rel="noopener"><?php esc_html_e( 'Documentation', 'ago-migrator' ); ?></a></li>
                            <li><a href="https://wordpress.org/documentation/article/moving-wordpress/" target="_blank" rel="noopener"><?php esc_html_e( 'Moving WordPress, official guide', 'ago-migrator' ); ?></a></li>
                            <li><a href="https://wordpress.org/documentation/article/changing-the-site-url/" target="_blank" rel="noopener"><?php esc_html_e( 'Changing the site URL', 'ago-migrator' ); ?></a></li>
                            <li><a href="https://pagespeed.web.dev/" target="_blank" rel="noopener"><?php esc_html_e( 'Compare speed before and after the move', 'ago-migrator' ); ?></a></li>
                        </ul>
                    </div>

                    <div class="card ago-card">
                        <h3><?php esc_html_e( 'About', 'ago-migrator' ); ?></h3>
                        <p style="font-size:13px;color:#666">
                            <?php esc_html_e( 'Full-site backup & migration plugin. Export everything, import anywhere. No limits, no subscriptions.', 'ago-migrator' ); ?>
                        </p>
                        <ul class="ago-features">
                            <li><?php esc_html_e( 'Complete database (all tables)', 'ago-migrator' ); ?></li>
                            <li><?php esc_html_e( 'Plugins, themes, uploads', 'ago-migrator' ); ?></li>
                            <li><?php esc_html_e( 'Users and passwords', 'ago-migrator' ); ?></li>
                            <li><?php esc_html_e( 'Serialization-safe URL replace', 'ago-migrator' ); ?></li>
                            <li><?php esc_html_e( 'Standard ZIP format', 'ago-migrator' ); ?></li>
                            <li><?php esc_html_e( 'WP-CLI support', 'ago-migrator' ); ?></li>
                            <li><?php esc_html_e( 'English, Spanish, Brazilian Portuguese', 'ago-migrator' ); ?></li>
                            <li><?php esc_html_e( 'Completely free, no Pro tier', 'ago-migrator' ); ?></li>
                        </ul>
                        <p style="margin-top:12px">
                            <a href="https://wordpress.org/support/plugin/ago-migrator/" target="_blank" rel="noopener">
                                <span class="dashicons dashicons-sos" style="vertical-align:middle;margin-right:4px"></span>
                                <?php esc_html_e( 'Support', 'ago-migrator' ); ?>
                            </a>
                        </p>
                    </div>

                    <div class="card ago-card">
                        <h3 style="margin-top:0"><?php esc_html_e( 'Other aGo Lab plugins', 'ago-migrator' ); ?></h3>
                        <p style="font-size:13px;color:#666;margin-top:0"><?php esc_html_e( 'Free WordPress plugins from the same team. No upsell pressure.', 'ago-migrator' ); ?></p>
                        <ul class="ago-features">
                            <li><strong>aGo Mail Pilot</strong>, <?php esc_html_e( 'Guided SMTP email delivery.', 'ago-migrator' ); ?></li>
                            <li><strong>aGo AI Chatbot</strong>, <?php esc_html_e( 'AI customer support widget for your site.', 'ago-migrator' ); ?></li>
                            <li><strong>aGo Legal</strong>, <?php esc_html_e( 'GDPR / LGPD / Chile Law 21.719 compliance toolkit.', 'ago-migrator' ); ?></li>
                            <li><strong>aGo Access</strong>, <?php esc_html_e( 'Accessibility toolbar and automatic fixes.', 'ago-migrator' ); ?></li>
                        </ul>
                        <p>
                            <a href="https://ago.cl/herramientas/" target="_blank" rel="noopener" class="button button-secondary" style="width:100%;text-align:center"><?php esc_html_e( 'Browse aGo Lab plugins', 'ago-migrator' ); ?></a>
                        </p>
                    </div>

                    <div class="card ago-card ago-donation">
                        <h3><?php esc_html_e( 'Support Open Source', 'ago-migrator' ); ?></h3>
                        <p style="font-size:13px;color:#666">
                            <?php esc_html_e( 'If this plugin saves you time, consider supporting our open-source work.', 'ago-migrator' ); ?>
                        </p>
                        <div class="ago-donation-amounts">
                            <a href="https://paypal.me/sixtovaldes/3" class="ago-amount" target="_blank" rel="noopener">$3</a>
                            <a href="https://paypal.me/sixtovaldes/5" class="ago-amount" target="_blank" rel="noopener">$5</a>
                            <a href="https://paypal.me/sixtovaldes/10" class="ago-amount" target="_blank" rel="noopener">$10</a>
                        </div>
                        <a href="https://paypal.me/sixtovaldes" class="ago-coffee-btn" target="_blank" rel="noopener">
                            <span class="dashicons dashicons-coffee" style="margin-right:6px"></span>
                            <?php esc_html_e( 'Buy us a coffee', 'ago-migrator' ); ?>
                        </a>
                        <p class="ago-donation-note">
                            <?php esc_html_e( 'Voluntary donation. Thank you!', 'ago-migrator' ); ?>
                        </p>
                    </div>

                    <div class="ago-footer">
                        <a href="https://ago.cl" target="_blank" rel="noopener" class="ago-footer-logo">
                            <img src="<?php echo esc_url( AGOMIGRATOR_URL . 'assets/img/agolab.webp' ); ?>" alt="aGo Lab" style="height:40px;width:auto">
                        </a>
                        <p>
                            <?php
                            echo wp_kses_post(
                                sprintf(
                                    /* translators: %1$s: heart, %2$s: link to ago.cl */
                                    __( 'Developed with %1$s by %2$s', 'ago-migrator' ),
                                    '<span style="color:#e25555">&#10084;</span>',
                                    '<a href="https://ago.cl" target="_blank" rel="noopener"><strong>aGo Lab</strong></a>'
                                )
                            );
                            ?>
                        </p>
                        <p style="font-size:11px;color:#999">
                            <?php esc_html_e( 'Building tools for the web, one plugin at a time.', 'ago-migrator' ); ?>
                        </p>
                    </div>

                </div>
            </div>

        </div>
        <?php
    }
}
